In [14]:
import numpy as np

In [15]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(data)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
print(data.shape)
print(data.size)
print(data.dtype)

(4, 3)
12
int64


In [17]:
 #data.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [10]:
import math

num = int(input("Enter a number: "))
alpha = (1 + math.sqrt(5))/2
beta = (1 - math.sqrt(5))/2
for i in range(num):
    fn = ((alpha**i) - (beta**i))/math.sqrt(5)
    print(round(fn))

0
1
1
2
3
5
8
13
21
34
55
89
